### ISSUE TITLE
PRIORITY 3.  Issues with ApI comparison page

### ISSUE THREAD

**Issue by iddmaxwell** [iddmaxwell/optimisebills#61]
PRIORITY 3. to do
duplicate comparison energy records are being created for Paul White. one set remains. 
one of status SWITCH_REQ_PROV 
the other has status switch now.  **Also noticed that the energy record type is not showing.**  

If the client clicks "request my switch is done for me" (not available on UK Power)
then create comparison record with status "req_we_switch"
If the client clicks "switch now" (IS available on UK Power)
then create comparison record with status "switch_now_prov"

Logged switch request for Iresa completing all fields but none of the details are showing on the switching tab.

**Comment by iddmaxwell** [comment]
Stlll getting the Oops error by clicking on the COMPARE NOW link in the emails.

Oops...an error has occurred.
We've logged it and will investigate. If it happens again please call 0845 130 3858 or e-mail us at customerservices@optimisebills.com - OptimiseBills Technical Support.

**Comment by iddmaxwell** [comment]
Gary Norton.
Clicking on comparisons shows generic error page:
"Thank you for the information. We will use this to create a new report for you so will be in touch when this is ready."  Web Team OptimiseBills 
indicates that creation of API link has not worked.  There is a UK Power id for the tariff in question - same tariff type Dual Fuel - although not for the same area.  However UK Power ids don't vary by area I believe, so it is possible to pick up the UK Power id for this tariff and use that in the API.  Is that what we are doing now or not?

**Comment by iddmaxwell** [comment]
Hi Will
Not sure if this notification is useful enough. Does it come to you or just me? 

Only part of the hyperlink is included in the link, so you can’t click on it to check. 

Also it doesn’t specify the client which is what I’d want to be able to look it up.

Ian

Ian Maxwell
M: +44 (0)7866 767630

From: OptimiseBills 
Sent: 18 February 2017 21:06
To: OptimiseBills <customerservices@optimisebills.com>
Subject: notification

Error Loading UKPower Quotes
URL: http://services.ukpower.co.uk/home_energy/api/quotes.xml?api_key=8B34-7EDA-E529-B25D-8755&limit=0&postcode=Wd49BY&compare_type=all_available&tariff_electricity=26611&postcode=Wd4 9BY&compare_type=all_available&tariff_electricity=26611&electricity_usage_kwh=4744&electricity_usage_method=kwh&electricity_plan_end_at=2016-01-17&fuel_type=electricity

**Comment by iddmaxwell** [comment]
We have still got the issue you mentioned today with the UK Power page not coming up for tariffs that are available on UK Power.  
For example on Ian Test70, I set the tariff to British Gas standard, chose SSE fixed 1 year to switch to and got the OB switching page, even though SSE is available on UK Power.

**Comment by iddmaxwell** [comment]
I was expecting that the screen "Would you like to receive the ongoing service of OptimiseBills?"
should come before the switching page, not after.
If it's easier to do, we could simply have this text on the same page, but at the top of the screen instead of the bottom.  So the logic is: 
If the tariff is NOT available on UK Power
   If the client clicks 'no' to signing up, we display a message
   "The service to organise this switch is only available to signed up clients.  Either click 'yes' to sign up or    contact the supplier directly yourself to arrange your switch."  
   If the client clicks "yes", then display all the data entry fields as now, but lower down the page.  
ELSE if the tariff IS available on UK Power
   capture client response "Yes" "No" "Maybe" to signing up. 
   allow client to click next and go to UK Power web site.

**Comment by Will-Newton** [comment]
done

**Comment by iddmaxwell** [comment]
we are still getting duplicate comparison records created as the client clicks through to 'switch now' or 'request my switch is done for me'.
