### ISSUE TITLE
PRIORITY 1 Switching pages

### ISSUE THREAD

**Issue by iddmaxwell** [iddmaxwell/optimisebills#68]
Priority 2+. 
DOB is not shown on Switching 2 tab.
email field is still too short
length of time at current address is not shown
Are the previous addresses on Switching 1 tab updated? Haven't tested yet.

**Comment by iddmaxwell** [comment]
PRIORITY 1.
Previous addresses on Switching 1 tab are not updated.
No alert or diary item to indicate client's request to switch.  There's only the diary item 'redirected to switch' and 'client self switching' but this doesn't show whether the screen has been completed or not.

**Comment by Will-Newton** [comment]
Billing address city/county blank
bank details missing

**Comment by Will-Newton** [comment]
Tested this again. Can't see anything wrong other than the Billing Address City/County isn't displaying which is fixed on the pilot site and will go live when I put the latest changes live.

**Comment by iddmaxwell** [comment]
what about the alerts?   Is that fixed too?

**Comment by iddmaxwell** [comment]
Billing address city/county is still not showing on pilot site.
No alert or diary item to indicate client has filled out the Switch Details page. 
Diary item 'client self switching' rather than 'client requests switch is done for me'

**Comment by Will-Newton** [comment]
Should be working now on pilot

**Comment by iddmaxwell** [comment]
Other issues look fine.  No email alerts appearing on pilot site.  Will there be an alert on the live site? 
However Billing address city/county is still not showing on pilot site.

**Comment by iddmaxwell** [comment]
PRIORITY 1.  Switch details 2 are not refreshed automatically. I have to manually refresh the page to remove previous client's switch details.  Unless I specifically refresh the switching page before saving there is a risk that I could overwrite a client's switch details with another.

**Comment by Will-Newton** [comment]
Tested it. Seems to be working on the live site.
